import { PORTRAIT_KEYBOARD_DATA } from '.';
import {
  Action,
  ButtonColor,
  ButtonSize,
  ButtonWrapperSize,
  IKeyboard,
} from '../types';

export const LANDSCAPE_KEYBOARD_DATA: IKeyboard[] = [
  {
    id: 'b425cc41-de1f-47bf-968f-55a54d09e30d',
    title: '(',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.LeftBraket,
    value: '(',
  },
  {
    id: 'dcab4bab-5603-43c5-9956-26c1db983ff0',
    title: ')',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.RightBraket,
    value: ')',
  },
  {
    id: 'ee655efc-df56-4e45-83c7-e5964f93c213',
    title: 'mc',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.MemoryClear,
    value: null,
  },
  {
    id: '0f2ec752-a4fc-4441-a423-3b70c9a44278',
    title: 'm+',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.MemoryAddValue,
    value: null,
  },
  {
    id: '6864e4fe-a43e-4b2d-9ae5-2bad7f298e2b',
    title: 'm-',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.MemorySubstractValue,
    value: null,
  },
  {
    id: 'c20d10ef-228b-428d-a212-d3d65beba7de',
    title: 'mr',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.MemoryReturn,
    value: null,
  },
  PORTRAIT_KEYBOARD_DATA[0],
  PORTRAIT_KEYBOARD_DATA[1],
  PORTRAIT_KEYBOARD_DATA[2],
  PORTRAIT_KEYBOARD_DATA[3],
  {
    id: '1b157547-20f4-4cd5-877c-fb24addb8e32',
    title: '2ⁿᵈ',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.SecondFunction,
    value: null,
  },
  {
    id: 'de3b3a5d-d231-4351-a5bc-137f56938ec4',
    title: 'x²',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Square,
    value: null,
  },
  {
    id: '6e67a713-1cc7-4e6d-bc53-9bd20de5acce',
    title: 'x³',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Cube,
    value: null,
  },
  {
    id: '282f44b9-78bc-4dd1-a75c-7ed18625fe34',
    title: 'xʸ',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Degree,
    value: null,
  },
  {
    id: '86b4b5de-df32-4fc4-9908-f907bb95d4ba',
    title: 'eˣ',
    secondTitle: 'yˣ',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Exponent,
    secondType: Action.DegreeBeforeNumber,
    value: null,
  },
  {
    id: 'e85d4fbe-d346-4ec4-96ae-69a3e715dcfc',
    title: '10ˣ',
    secondTitle: '2ˣ',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.TenInDegree,
    secondType: Action.TwoInDegree,
    value: null,
  },
  PORTRAIT_KEYBOARD_DATA[4],
  PORTRAIT_KEYBOARD_DATA[5],
  PORTRAIT_KEYBOARD_DATA[6],
  PORTRAIT_KEYBOARD_DATA[7],
  {
    id: 'f606ffc5-2939-4843-b570-024128955837',
    title: '¹/ₓ',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.RatioToDivision,
    value: null,
  },
  {
    id: 'ba5e6872-05b4-481f-a216-5563c605ce17',
    title: '√x',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.SquareRoot,
    value: null,
  },
  {
    id: 'f56bfe36-8da0-453e-8a3f-b55557064e85',
    title: '∛x',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.CubeRoot,
    value: null,
  },
  {
    id: 'cc6567e6-4009-4c2b-bbc9-347ee6a4d182',
    title: 'ʸ√x',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.RootByNumber,
    value: null,
  },
  {
    id: '763d689a-a1b8-46ae-b98d-d4cdcbc5c877',
    title: 'ln',
    secondTitle: 'logₓ',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Logarithm,
    secondType: Action.NumberLogaritm,
    value: null,
  },
  {
    id: '71379094-1210-43cf-9764-40394e2b95e0',
    title: 'log₁₀',
    secondTitle: 'log₂',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.TenLogarithm,
    secondType: Action.TwoLogarithm,
    value: null,
  },
  PORTRAIT_KEYBOARD_DATA[8],
  PORTRAIT_KEYBOARD_DATA[9],
  PORTRAIT_KEYBOARD_DATA[10],
  PORTRAIT_KEYBOARD_DATA[11],
  {
    id: '83f3d8e3-a0ca-4cfc-84eb-46c561aadab6',
    title: 'x!',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Factorial,
    value: null,
  },
  {
    id: '541595dd-f040-41e7-ac88-2fbbe71575d2',
    title: 'sin',
    secondTitle: 'sin⁻¹',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Sine,
    secondType: Action.InverseSine,
    value: null,
  },
  {
    id: 'bb7bb393-c5c7-4150-a4e6-56dfa8b58fb4',
    title: 'cos',
    secondTitle: 'cos⁻¹',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Cosine,
    secondType: Action.InverseCosine,
    value: null,
  },
  {
    id: '709e4fd3-e948-400e-9d16-136b0492106e',
    title: 'tan',
    secondTitle: 'tan⁻¹',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Tangent,
    secondType: Action.InverseTangent,
    value: null,
  },
  {
    id: '00cf4102-7182-42b6-a7e1-073d07775147',
    title: 'e',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Euler,
    value: String(Math.E),
  },
  {
    id: '545598e5-46c1-48f6-8818-4b2341c95b49',
    title: 'EE',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.EnterExponent,
    value: null,
  },
  PORTRAIT_KEYBOARD_DATA[12],
  PORTRAIT_KEYBOARD_DATA[13],
  PORTRAIT_KEYBOARD_DATA[14],
  PORTRAIT_KEYBOARD_DATA[15],
  {
    id: '987721ad-f8a9-490d-9101-adc4198fd9cc',
    title: 'Deg',
    secondTitle: 'Rad',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Mode,
    value: null,
  },
  {
    id: '881b9278-3bd4-42f8-9f26-5ad0b28ec12a',
    title: 'sinh',
    secondTitle: 'sinh⁻¹',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.HyperSine,
    secondType: Action.InverseHyperSine,
    value: null,
  },
  {
    id: '9489945e-def4-4a4c-8d8c-50b83457e980',
    title: 'cosh',
    secondTitle: 'cosh⁻¹',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.HyperCosine,
    secondType: Action.InverseHyperCosine,
    value: null,
  },
  {
    id: '7035dd2a-f7f5-496e-97b0-24d0d52fe8e3',
    title: 'tanh',
    secondTitle: 'tanh⁻¹',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.HyperTangent,
    secondType: Action.InverseHyperTangent,
    value: null,
  },
  {
    id: 'c1460b13-641a-414f-9410-295cce289210',
    title: 'π',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Pi,
    value: String(Math.PI),
  },
  {
    id: 'fa18f408-51f5-4fad-ae62-637ace963adb',
    title: 'Rand',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Landscape,
    },
    type: Action.Random,
    value: null,
  },
  PORTRAIT_KEYBOARD_DATA[16],
  PORTRAIT_KEYBOARD_DATA[17],
  PORTRAIT_KEYBOARD_DATA[18],
];
