import {
  Action,
  ButtonColor,
  ButtonPressed,
  ButtonSize,
  ButtonWrapperSize,
  Keyboard,
} from '../types';

export const portraitKeyboardData: Keyboard[] = [
  {
    id: '197162aa6-6408-4520-9877-da4ab4ad518b',
    title: 'AC',
    secondTitle: 'C',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Additional,
    },
    type: Action.AllClear,
    value: null,
  },
  {
    id: '5660228f-d41d-4a2b-b41b-924db3ac1203',
    title: '±',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Additional,
    },
    type: Action.ChangeSign,
    value: null,
  },
  {
    id: 'acef068b-856e-48eb-8caf-86a902afaf83',
    title: '%',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Additional,
    },
    type: Action.GetPercentage,
    value: null,
  },
  {
    id: '86e47f33-63a8-4ee8-b438-74d324c87fdc',
    title: '/',
    isToggler: true,
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Operator,
      buttonState: ButtonPressed.Operator,
    },
    type: Action.Division,
    value: null,
  },
  {
    id: '29068acc-9532-42ee-b879-d403c70c64f2',
    title: '7',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '7',
  },
  {
    id: '908f2051-a226-4239-b1fb-cf1f6197afb8',
    title: '8',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '8',
  },
  {
    id: 'f017e132-905f-494a-9047-f66322e13255',
    title: '9',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '9',
  },
  {
    id: 'b07073fd-f33a-4c09-a11a-438da3045776',
    title: '×',
    isToggler: true,
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Operator,
      buttonState: ButtonPressed.Operator,
    },
    type: Action.Multiplication,
    value: null,
  },
  {
    id: '8e1b4343-041e-425f-843c-5ab73068e76d',
    title: '4',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '4',
  },
  {
    id: '74b67158-70b4-4f41-a247-1ccbf0c68aea',
    title: '5',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '5',
  },
  {
    id: 'ee7e5544-920f-4f51-a852-65f62a17f235',
    title: '6',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '6',
  },
  {
    id: '7737de9d-9e22-4bb6-8124-bd2349566e1c',
    title: '-',
    isToggler: true,
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Operator,
      buttonState: ButtonPressed.Operator,
    },
    type: Action.Subtraction,
    value: null,
  },
  {
    id: '4e257f18-b173-4c08-877c-cb75cbed1430',
    title: '1',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '1',
  },
  {
    id: 'af3d33d6-ec41-46e4-bf66-70e87da2baeb',
    title: '2',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '2',
  },
  {
    id: '4c4b438c-9f86-4aa7-821e-aed07c71e978',
    title: '3',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '3',
  },
  {
    id: '75586991-9ee9-40b1-b5e1-dfedabd7282d',
    title: '+',
    isToggler: true,
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Operator,
      buttonState: ButtonPressed.Operator,
    },
    type: Action.Addition,
    value: null,
  },
  {
    id: 'a327a204-baca-401f-a353-e4d4da455472',
    title: '0',
    classes: {
      wrapperSize: ButtonWrapperSize.Big,
      buttonSize: ButtonSize.Big,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '0',
  },
  {
    id: 'ce07dd45-8d63-4ed6-ac4d-b6a3a4f678e6',
    title: ',',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Default,
    },
    type: Action.Number,
    value: '.',
  },
  {
    id: 'f414bb95-83a9-4fc8-a355-7baeb5915350',
    title: '=',
    classes: {
      wrapperSize: ButtonWrapperSize.Default,
      buttonSize: ButtonSize.Default,
      buttonColor: ButtonColor.Operator,
    },
    type: Action.Equal,
    value: null,
  },
];
